services:
  mariadb-service:
    restart: always
    image: mariadb
    container_name: mariadb-compose
    ports:
      - '4444:3306'
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
    volumes:
      - ../../sql/netflux.sql:/docker-entrypoint-initdb.d/netflux.sql
      - mariadb_vol:/var/lib/mysql

  backend-service:
    restart: always
    build:
      context: ../../
      dockerfile: Dockerfile
    container_name: backend-compose
    ports:
      - '6969:8080'
    depends_on:
      - mariadb-service
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${MARIADB_USER}
      SPRING_DATASOURCE_PASSWORD: ${MARIADB_ROOT_PASSWORD}

volumes:
  mariadb_vol: