SET
REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE ACTORS RESTART IDENTITY;
TRUNCATE TABLE FILM RESTART IDENTITY;
TRUNCATE TABLE DIRECTORS RESTART IDENTITY;
TRUNCATE TABLE FILM_ACTOR RESTART IDENTITY;

SET
REFERENTIAL_INTEGRITY TRUE;