name: SpringBoot tests

on:
  push:
    branches: "master"
  pull_request:
    branches: "master"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        
      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven
          
      - name: Install dependencies
        run: mvn clean install -DskipTests
  
      - name: Run tests
        run: mvn test || true
      
      - name: Generate Test reports
        if: always()
        run: mvn surefire-report:report

      - name: Upload Test Report (if failed)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: target/site/surefire-report.html
